name: PermitReady
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 11.0.0

settings:
  base:
    # Using Swift 5.10 for better compatibility with Google Mobile Ads SDK
    # which doesn't fully support Swift 6 concurrency yet
    SWIFT_VERSION: "5.10"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "" # Add your team ID here
    CODE_SIGN_STYLE: Automatic
    SWIFT_STRICT_CONCURRENCY: minimal

targets:
  PermitReady:
    type: application
    platform: iOS
    sources:
      - path: PermitReady
        excludes:
          - "**/*.md"
    resources:
      - path: PermitReady/Resources
      - path: PermitReady/Core/Data/QuestionBanks
        type: folder
    settings:
      base:
        INFOPLIST_FILE: PermitReady/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.permitready
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: GoogleMobileAds
    
  PermitReadyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PermitReadyTests
    dependencies:
      - target: PermitReady
    settings:
      base:
        INFOPLIST_FILE: PermitReadyTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.permitready.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PermitReady.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/PermitReady"
        BUNDLE_LOADER: "$(TEST_HOST)"

  PermitReadyUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PermitReadyUITests
    dependencies:
      - target: PermitReady
    settings:
      base:
        INFOPLIST_FILE: PermitReadyUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.permitready.uitests
        TEST_TARGET_NAME: PermitReady

schemes:
  PermitReady:
    build:
      targets:
        PermitReady: all
        PermitReadyTests: [test]
        PermitReadyUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": true
      storeKitConfiguration: PermitReady.storekit
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - PermitReadyTests
        - PermitReadyUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
